### ISSUE TITLE
 I can't seem to open the data address you gave me

### ISSUE THREAD

**Issue by genbei** [lena-voita/good-translation-wrong-in-context#11]
Hello, I can't seem to open the data address you gave me. Is there a problem with the link? Can you send me a copy of the data

**Comment by lena-voita** [comment]
Hi,

As far as I know, the links are fine: other people used it, and I've checked right now it leads where it should - to the dropbox.

Is it possible that you are located somewhere where dropbox does not work in general?

**Comment by genbei** [comment]
> 你好
> 
> 据我所知，链接很好：其他人使用了它，我现在已经检查了它在应该到的地方-到保管箱。
> 
> 您是否可能位于Dropbox通常无法正常工作的地方？

Thank you. You're right
